baseURL = "https://riseofthecontainers.github.io/"
languageCode = "en-us"
copyright = "2020 sunitparekh.in"
theme = "learn"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true

[params]
  editURL = "https://github.com/riseofthecontainers/website"
  description = "Rise of the Containers"
  author = "Sunit Parekh"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false

[outputs]
home = [ "HTML", "RSS", "JSON"]

[Languages]
[Languages.en]
title = "Rise of the Containers"
weight = 1
languageName = "English"

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> GitHub repo"
identifier = "ds"
url = "https://github.com/riseofthecontainers/website"
weight = 10


[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-fw fa-bookmark'></i> Kubernetes Documentation"
identifier = "kubedoc"
url = "https://kubernetes.io/docs/home/"
weight = 20

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-fw fa-bullhorn'></i> Credits"
url = "/credits"
weight = 30
